config/routes.rb
Rails.application.routes.draw do


  resources :memberships

  resources :newsletters

  resources :subscribers

  get 'dashboards/show'

  resources :messages
  resources :invoices

  resources :line_items


  resources :sessions
  resources :users

  resources :posts do
  resources :comments
  end

  resources :users do
   collection do
     post 'search', to: 'users#search'
   end
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  get 'pages/about'

  get 'pages/leadership'

  get 'pages/contact'

  get 'pages/small_businesses'

  get 'pages/corporate'

  get 'pages/government'

  get 'welcome/index'
  get 'pages/core_values'
  get 'pages/services'
  get 'pages/company_profile'



  root 'welcome#index'





end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  body       :text
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id             :integer          not null, primary key
#  invoice_number :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  user_id        :integer
#  amount_paid    :decimal(, )
#

class Invoice < ActiveRecord::Base
  belongs_to :user
  has_many :line_items
  accepts_nested_attributes_for :line_items, allow_destroy: true


  def total_price
    # convert to array so it doesn't try to do sum on database directly
    line_items.to_a.sum(&:full_price)
  end

  scope :sales, -> { where.not(amount_paid: nil)}
end

app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  amount     :decimal(, )
#  quantity   :integer
#  invoice_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class LineItem < ActiveRecord::Base
  belongs_to :invoice

  def full_price
    amount * quantity
  end
end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  business_name   :string(255)
#  phone           :string(255)
#  email           :string(255)
#  business_needs  :text
#  business_issues :text
#  created_at      :datetime
#  updated_at      :datetime
#

class Membership < ActiveRecord::Base
end

app/models/message.rb
class Message
  include ActiveAttr::Model

  attribute :name
  attribute :subject
  attribute :email
  attribute :content
  attribute :priority # type: Integer, default: 0

  validates_presence_of :name, :subject
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500
end

app/models/newsletter.rb
# == Schema Information
#
# Table name: newsletters
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Newsletter < ActiveRecord::Base
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  has_many :comments
end

app/models/subscriber.rb
# == Schema Information
#
# Table name: subscribers
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Subscriber < ActiveRecord::Base

  scope :pull, -> { Subscriber.pluck(:email) }

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  first_name       :string(255)
#  last_name        :string(255)
#  business_name    :string(255)
#  business_address :string(255)
#  email            :string(255)
#  phone            :string(255)
#  admin            :boolean
#  password_digest  :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#  naics_code       :integer
#  industry         :string(255)
#

class User < ActiveRecord::Base
  has_many :invoices

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false}
  validates :password, length: { minimum: 6}
  validates :last_name, :first_name, :industry, presence: true
  validates :naics_code, length: { minimum: 6}, numericality: { only_integer: true }
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:first_name, :last_name, :business_name, :phone, :email, :business_needs, :business_issues)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/memberships/_form.html.erb
<div class="signup">
<h1>New membership</h1>
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :business_name %>
    <%= f.text_field :business_name %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :business_needs %>
    <%= f.text_area :business_needs %>
  </div>
  <div class="field">
    <%= f.label :business_issues %>
    <%= f.text_area :business_issues %>
  </div>


  <div class="field">
    <%= label_tag :card_number, "Card Number" %>
    <%= text_field_tag :card_number, nil, { name: nil, :'data-stripe' => "number", class: "form-control" } %>
  </div>
  <div class="field">
    <%= label_tag :card_code, "CVV Number" %>
    <%= text_field_tag :card_code, nil, { name: nil, :'data-stripe' => "cvc", class: "form-control" } %>
  </div>
  <div class="field">
    <%= label_tag :card_month, "Expiration" %>
    <%= select_month nil, {add_month_numbers: true}, {name: nil, :'data-stripe' => "exp-month", class: "form-control" }  %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, :'data-stripe' => "exp-month", class: "form-control" } %>
  </div>
<hr>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 </div>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing memberships</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Business name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Business needs</th>
      <th>Business issues</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.first_name %></td>
        <td><%= membership.last_name %></td>
        <td><%= membership.business_name %></td>
        <td><%= membership.phone %></td>
        <td><%= membership.email %></td>
        <td><%= membership.business_needs %></td>
        <td><%= membership.business_issues %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @membership.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @membership.last_name %>
</p>

<p>
  <strong>Business name:</strong>
  <%= @membership.business_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @membership.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @membership.email %>
</p>

<p>
  <strong>Business needs:</strong>
  <%= @membership.business_needs %>
</p>

<p>
  <strong>Business issues:</strong>
  <%= @membership.business_issues %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>