config/routes.rb
Rails.application.routes.draw do


  resources :memberships

  resources :newsletters

  resources :subscribers

  get 'dashboards/show'

  resources :messages
  resources :invoices

  resources :line_items


  resources :sessions
  resources :users

  resources :posts do
  resources :comments
  end

  resources :users do
   collection do
     post 'search', to: 'users#search'
   end
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  get 'pages/about'

  get 'pages/leadership'

  get 'pages/contact'

  get 'pages/small_businesses'

  get 'pages/corporate'

  get 'pages/government'

  get 'welcome/index'
  get 'pages/core_values'
  get 'pages/services'
  get 'pages/company_profile'



  root 'welcome#index'





end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  body       :text
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id             :integer          not null, primary key
#  invoice_number :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  user_id        :integer
#  amount_paid    :decimal(, )
#

class Invoice < ActiveRecord::Base
  belongs_to :user
  has_many :line_items
  accepts_nested_attributes_for :line_items, allow_destroy: true


  def total_price
    # convert to array so it doesn't try to do sum on database directly
    line_items.to_a.sum(&:full_price)
  end

  scope :sales, -> { where.not(amount_paid: nil)}
end

app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  amount     :decimal(, )
#  quantity   :integer
#  invoice_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class LineItem < ActiveRecord::Base
  belongs_to :invoice

  def full_price
    amount * quantity
  end
end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  business_name   :string(255)
#  phone           :string(255)
#  email           :string(255)
#  business_needs  :text
#  business_issues :text
#  created_at      :datetime
#  updated_at      :datetime
#

class Membership < ActiveRecord::Base
end

app/models/message.rb
class Message
  include ActiveAttr::Model

  attribute :name
  attribute :subject
  attribute :email
  attribute :content
  attribute :priority # type: Integer, default: 0

  validates_presence_of :name, :subject
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500
end

app/models/newsletter.rb
# == Schema Information
#
# Table name: newsletters
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Newsletter < ActiveRecord::Base
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  has_many :comments
end

app/models/subscriber.rb
# == Schema Information
#
# Table name: subscribers
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Subscriber < ActiveRecord::Base

  scope :pull, -> { Subscriber.pluck(:email) }

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  first_name       :string(255)
#  last_name        :string(255)
#  business_name    :string(255)
#  business_address :string(255)
#  email            :string(255)
#  phone            :string(255)
#  admin            :boolean
#  password_digest  :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#  naics_code       :integer
#  industry         :string(255)
#

class User < ActiveRecord::Base
  has_many :invoices

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false}
  validates :password, length: { minimum: 6}
  validates :last_name, :first_name, :industry, presence: true
  validates :naics_code, length: { minimum: 6}, numericality: { only_integer: true }
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoice = Invoice.all
  end

  def new
    @invoice = Invoice.new
    @invoice.line_items.build
  end

  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@invoice, view_context)
        send_data pdf.render, filename: "invoice_#{@invoice.invoice_number}.pdf",
                  type: "application/pdf",
                  disposition: "inline"
      end
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:invoice_number, :user_id, line_items_attributes: [:name, :amount, :quantity, :id, :destroy] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>

      <div class="field">
      <%= f.label :Client %>
      <%= f.collection_select :user_id, User.order(:business_name), :id, :business_name, include_blank: true %><br><br>
      </div>
      <div class="field">
      <%= f.label :invoice_number %>
      <%= f.text_field :invoice_number %>
      </div>

     <div class="field">
      <%= f.fields_for :line_items do |builder| %>
      <%= render 'line_item_fields', f: builder %>
    <% end %>
    </div>

    <%= link_to_add_fields "Add Item", f, :line_items %>
    <div class="actions">
          <%= f.submit %>
    </div>
      <% end %>

</div>

app/views/invoices/_line_item_fields.html.erb
    <div class="field">
      <%= f.label   :name %>
      <%= f.text_field :name %>
      </div>
      <div class="field">

      <%= f.label   :quantity %>
      <%= f.text_field :quantity %>
</div><div class="field">


      <%= f.label   :amount %>
      <%= f.text_field :amount %>

</div>

      <%= f.hidden_field :_destroy %>
      <%= link_to 'Remove Item', '#', class: "remove_fields" %>
    </fieldset>

app/views/invoices/index.html.erb
<div class="signup"><h1>Invoices</h1>

<table>
  <tbody>
<% @invoice.each do |invoice| %>
  <tr>
  <td><%= invoice.invoice_number %></td>
  <td><%= invoice.user.business_name %></td>
  <td><%= invoice.created_at.strftime('%B, %d, %Y') %></td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/invoices/new.html.erb
<div class="signup"><h1>New Invoice</h1>

<%= render 'form' %>

app/views/invoices/show.html.erb
<h1>Order #<%= @invoice.invoice_number %></h1>

<table id="line_items">
  <tr>
    <th>Name</th>
    <th>Qty</th>
    <th class="price">Amount</th>
    <th class="price">Total Amount</th>
  </tr>
  <% @invoice.line_items.each do |line_item| %>
      <tr class="<%= cycle :odd, :even %>">
        <td><%= line_item.name %></td>
        <td class="qty"><%= line_item.quantity %></td>
        <td class="price"><%= number_to_currency(line_item.amount) %></td>
        <td class="price"><%= number_to_currency(line_item.full_price) %></td>
      </tr>
  <% end %>
  <tr>
    <td class="total price" colspan="4">
      Amount Due: <%= number_to_currency(@invoice.total_price) %>
    </td>
  </tr>
</table>

<p><%= link_to "Printable Receipt (PDF)", invoice_path(@invoice, format: "pdf") %></p>